[project]
name = "mcp-inspector"
version = "0.1.0"
description = "Hello World MCP Inspector"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Krishna Manchikalapudi"},
]
dependencies = [
   "fastapi",
    "mcp[cli]",
    "uvicorn",
    "httpx",
]

[project.urls]
Homepage = "https://dayone.dev"
Repository = "https://github.com/krishnamanchikalapudi/examples.py/LLM/MCP/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "hatchling",
    "pytest",
    "pytest-asyncio",
    "ruff",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.ruff]
line-length = 120
target-version = "py310"
extend-exclude = ["README.md"]

[tool.ruff.lint]
select = [
    "C4",   # flake8-comprehensions
    "C90",  # mccabe
    "E",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
    "PERF", # Perflint
    "PL",   # Pylint
    "UP",   # pyupgrade
]
ignore = ["PERF203", "PLC0415", "PLR0402"]
mccabe.max-complexity = 24 # Default is 10

[tool.ruff.lint.pylint]
allow-magic-value-types = ["bytes", "float", "int", "str"]
max-args = 23                                              # Default is 5
max-branches = 23                                          # Default is 12
max-returns = 13                                           # Default is 6
max-statements = 102                                       # Default is 50
